# Generated by Django 6.0.4 on 2026-04-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_audio_artist_post_audio_name_post_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_link',
            field=models.URLField(blank=True),
        ),
    ]
